# Generated by Django 5.2.1 on 2025-05-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
